os:
  - linux
  - osx
  - windows
language: node_js
node_js: lts/*
script: npm test
after_success: npm run coverage
jobs:
  include:
    - stage: deploy
      before_script: npm run build
      script: npx semantic-release
      if: branch = master
