os:
  - linux
  - osx
  - windows
language: node_js
node_js: lts/*
script: npm test -- --coverage
after_success: if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then npm run coverage; fi
jobs:
  include:
    - stage: deploy
      before_script: npm run build
      script: npx semantic-release
      if: branch = master
